<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>31-手写promise-14-自定义封装-reject方法封装</title>
  </head>
  <body></body>
  <script>
    function Promise(executor) {
      // 添加属性
      this.PromiseState = 'pending'
      this.PromiseResult = null
      // 声明一个属性
      this.callback = []
      // 保存实例对象的this值
      const self = this
      // 执行器函数在内部是同步调用的
      function resolve(data) {
        // 增加判断状态逻辑
        if (self.PromiseState !== 'pending') {
          return
        }
        // 修改对象的状态(promiseState)
        self.PromiseState = 'fulfilled'
        // 设置对象的结果值(promiseResult)
        self.PromiseResult = data
        // 调用成功的回调函数
        if (self.callback.length > 0) {
          self.callback.forEach((item) => {
            item.onResolved(data)
          })
          // self.callback = []
        }
      }

      function reject(error) {
        if (self.PromiseState !== 'pending') {
          return
        }
        self.PromiseState = 'rejected'
        self.PromiseResult = error
        // 调用失败的回调函数
        if (self.callback.length > 0) {
          self.callback.forEach((item) => {
            item.onRejected(error)
          })
          // self.callback = []
        }
      }
      try {
        executor(resolve, reject)
      } catch (error) {
        // 修改 promise 的状态为失败
        reject(error)
      }
    }

    // 添加 then 方法
    Promise.prototype.then = function (onResolved, onRejected) {
      const self = this
      // onRejected、onRejected 兼容处理为空时候的处理
      if (typeof onRejected !== 'function') {
        onRejected = (reason) => {
          throw reason
        }
      }

      if (typeof onResolved !== 'function') {
        onResolved = (value) => value
      }
      return new Promise((resolve, reject) => {
        function callback(typeFunc) {
          try {
            let result = typeFunc(self.PromiseResult)
            if (result instanceof Promise) {
              result.then(
                (v) => {
                  resolve(v)
                },
                (e) => {
                  reject(e)
                },
              )
            } else {
              // 结果的对象状态为成功
              resolve(result)
            }
          } catch (error) {
            reject(error)
          }
        }
        if (this.PromiseState === 'fulfilled') {
          callback(onResolved)
        } else if (this.PromiseState === 'rejected') {
          callback(onRejected)
        }
        // 增加pending 的一个判断
        if (this.PromiseState === 'pending') {
          // 需要保存回调函数
          this.callback.push({
            onResolved: function () {
              // console.log('success')
              // 执行成功的回调函数
              callback(onResolved)
            },
            onRejected: function () {
              callback(onRejected)
            },
          })
        }
      })
    }

    Promise.prototype.catch = function (onRejected) {
      return this.then(undefined, onRejected)
    }
    // 不属于函数实例，是构造函数方法
    Promise.resolve = function (resultVal) {
      // 返回 promise
      return new Promise((resolve, reject) => {
        if (resultVal instanceof Promise) {
          resultVal.then(
            (v) => {
              resolve(v)
            },
            (err) => {
              reject(err)
            },
          )
        } else {
          resolve(resultVal)
        }
      })
    }
    Promise.reject = function (rejectVal) {
      // 这里不用做如下处理，暂时留个疑问
      // return new Promise((resolve, reject) => {
      //   if (rejectVal instanceof Promise) {
      //     rejectVal.then(
      //       ((result) => {
      //         resolve(result)
      //       },
      //       (error) => {
      //         reject(error)
      //       })
      //     )
      //   } else {
      //     reject(rejectVal)
      //   }
      // })
      return new Promise((resolve, reject) => {
        reject(rejectVal)
      })
    }
  </script>
  <script>
    const p1 = Promise.reject('error啊')
    console.log(p1)
    const p2 = Promise.reject(
      new Promise((resolve, reject) => {
        // reject('error我是错误信息')
      }),
    )
    console.log(p2)
    const p3 = Promise.reject(Promise.resolve('我是resolve信息'))
    console.log(p3)
    const p4 = Promise.reject(Promise.reject('我是错误信息'))
    console.log(p4)
  </script>
</html>
